services:
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  postgres:
    image: postgis/postgis:17-3.4
    container_name: postgres_postgis
    restart: always
    environment:
      POSTGRES_USER: proiectIP
      POSTGRES_PASSWORD: proiectIP
      POSTGRES_DB: proiectIP
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
